# Generated by Django 4.0.6 on 2022-08-24 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDisqueria', '0003_remove_vinilo_indnacional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='indNacional',
        ),
    ]
